# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: In 3years
subtitle: ''
description: '데이터와 NLP를 통해 서로를 연결하고 싶습니다'
keywords: natural-language-processing, nlp, summarization, topic-modeling, machine-learning, data-analysis, review, paper, study, 자연어처리, 요약, 토픽모델링, 머신러닝, 데이터분석, 리뷰, 논문, 
email: uoneway@gmail.com
author: Hangil Kim
language: kr
timezone: 'Asia/Seoul'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://uoneway.github.io/
root: /
permalink: :year/:month/:title/
# permalink: /:category/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: categorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/uoneway/uoneway.github.io.git
  branch: master

# sitemap auto generator
sitemap:
    path: sitemap.xml

# rss feed auto generator
feed:
  type: atom
  path: feed.xml
  limit: 20

# hexo-katex
# https://github.com/thcd/hexo-katex
pandoc:
  mathEngine: katex
katex:
  css: false
  throw_on_error: false

# robots
robotstxt:
  useragent: "*"
  allow:
    - /
  sitemap: https://uoneway.github.io/sitemap.xml

# 포스트에서 참고하고 있는 외부링크에 nofollw 속성을 자동으로 추가
nofollow:
    enable: true
    exclude:
    - exclude_1.com
    - exclude_2.com